# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
#
# Continuous Integration and Deployment   https://travis-ci.com
# Code Quality Coverage                   https://codeclimate.com
#
# Thanks for your services, guys (c) Yurii K.
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
language: php
php:
  - '5.6'
  - '7.0'
  - '7.1'
  - 'nightly'
matrix:
  allow_failures:
    - php: nightly
#
# build lifecycle
#
before_install:
  - if git log -1 --oneline | grep -qie "\[sc\]"; then echo -e "\e[0;34;40m[sc] is presented. clover will not be set"; else export CLOVER="--coverage-clover ../../build/logs/clover.xml"; fi
install:
  - bash .travis.sh install
before_script:
script:
  - bash .travis.sh script
after_success:
  - bash .travis.sh after_success
after_failure:
after_script:
before_deployment:
deployment:
after_deployment:
#
# other
#
addons:
  code_climate:
    repo_token: 2a836d2f2a68e75e3e61a1c3dd49a19592afb2ee294c9c585161df520936a23a
#
# cache on success
#
cache:
  directories:
    - vendor
#
# for Docker, use of new container-based stack
#
sudo: false
#
# for git client on Travis
#
git:
  submodules: false