services:
    App\Sitemap:
        class: 'App\Sitemap'
        public: true
        arguments:
            $sitemap_filename: '%kernel.project_dir%/tests/_data/tmp/sitemap_test.xml'
            $logsDir: '%kernel.project_dir%/tests/_data/logs'
            $request_stack: '@request_stack'